### ISSUE TITLE
Unable to find sample app in token browser

### ISSUE THREAD

**Issue by hiddentao** [tokenbrowser/token-app-js#12]
I followed the instructions at http://developers.tokenbrowser.com/docs/creating-a-token-app

Setup the following env vars:

      - TOKEN_APP_ID=0xa8d59db090f35726bcfd3fa1c1b05316725e1990
      - TOKEN_APP_PAYMENT_ADDRESS=0x49d4c4aac28ee9576d029481ffd434d2b7b336e3
      - TOKEN_APP_USERNAME=hiddentao-sample-app

`docker-compose up` worked ok. 

But when I search for "hiddentao-sample-app" in the Token Browser I get nothing. Scanning the QR code on the seed generator page doesn't work either. Do I have to set all the env vars in the docker compose file?

**Comment by faymontage** [comment]
All of the "Required variables" listed here must be set: http://developers.tokenbrowser.com/docs/configuration

Does doing so solve your issue?

**Comment by hiddentao** [comment]
@faymontage No it doesn't. I have all the required variables set. The relevant portion of my docker-compose.yml:

```
version: '2'
services:
  headless-client:
    build: dependencies/headless-client
    links:
      - redis
      - postgres
    environment: &environment
      - TOKEN_APP_ID=0xa8d59db090f35726bcfd3fa1c1b05316725e1990
      - TOKEN_APP_PAYMENT_ADDRESS=0x49d4c4aac28ee9576d029481ffd434d2b7b336e3
      - TOKEN_APP_USERNAME=hiddentao-sample-app
      - TOKEN_APP_NAME=hiddentao-sample-app
      - TOKEN_APP_AVATAR=
      - TOKEN_APP_SEED=island kidney hockey nest alcohol voice move memory problem author fine release
...
```
